name: Generate GitHub Profile Animations

on:
  # Tự động chạy vào nửa đêm mỗi ngày
  schedule:
    - cron: "0 0 * * *" 
  # Cho phép bạn bấm nút chạy thủ công
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cấp quyền cho bot lưu file ảnh vào repo
    
    steps:
      # 1. Kéo code về
      - uses: actions/checkout@v3

      # 2. Tạo hình 3D
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # 3. Tạo con sâu chuyển động
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}

      # 4. Lưu ảnh và đẩy (push) lên lại Github
      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "Auto-generate 3D graph and Snake" || exit 0
          git push
